### PR TITLE
Implement AlephiumClient + Database Layer

### LINKED ISSUE #1: Implement AlephiumClient for Blockchain Data Fetching
**Objective**
Create a robust and reusable Rust client for interacting with Alephium nodes, providing a foundation for the indexer to fetch and process blockchain data efficiently.

**Scope of Work**
1. HTTP Client Implementation
- Implement async HTTP client using reqwest/hyper
- Create typed responses for Alephium API endpoints
- Add proper error handling and retry mechanisms
- Implement connection pooling and timeout management

2. Blockchain Data Types
- Create Rust types for blocks, transactions, and events
- Implement serialization/deserialization using serde
- Add validation for blockchain data structures
- Create helper methods for data conversion

3. Node Communication
- Implement WebSocket subscription for new blocks
- Add methods for fetching historical blocks
- Create batch processing capabilities
- Implement rate limiting and backoff strategies

**Requirements**
- Code should be async-first and properly handle concurrency
- Comprehensive error handling with custom error types
- Complete test suite with mocked responses
- Documentation for all public interfaces
- Configuration through environment variables

### LINKED ISSUE #2: Implement Database Layer with Diesel and PostgreSQL
**Objective**
Create a robust database layer using Diesel ORM and PostgreSQL to store and manage indexed blockchain data efficiently, ensuring data consistency and quick querying capabilities.

**Scope of Work**
1. Schema Design
- Define tables for blocks, transactions, and events
- Create necessary migrations using Diesel
- Implement indexes for optimal query performance
- Design schema to support future extensions

2. Model Implementation
- Create Diesel models for all entities
- Implement relationships between models
- Add validation and conversion methods
- Create helper methods for common queries

3. Connection Management
- Implement connection pooling
- Add transaction management
- Implement proper error handling

**Requirements**
- Properly managed database migrations
- Optimized schema design for typical queries
- Complete test suite with test database

### PR DESCRIPTION
**Pull request by TropicalDog17**
### Overview 

- [x] Closes #1 
- [x] Closes #2

### CODE REVIEW

**Comment by TropicalDog17** [comment]
Hi @raduciobanu22, just to let you know, @htiennv and me will collaborate to work on the issue #1 and #2 and will deliver in this single PR. I myself will try to finish the DB layer early, maybe tomorrow.

For now can you check the current status of the code and leave some reviews for @htiennv?

**Comment by htiennv** [comment]
Hi @raduciobanu22 , I'm doing some refactors on this PR. I will ping you when its ready for review. Thanks

**Comment by TropicalDog17** [comment]
@raduciobanu22 Hi, can you take a look at our work so far, if there's anything missing please let us know, thanks!

**Comment by raduciobanu22** [comment]
> @raduciobanu22 Hi, can you take a look at our work so far, if there's anything missing please let us know, thanks!

I guess support for the streaming endpoints is what's missing at this point. As the indexer service will need to open a ws connection and process incoming blocks.
https://docs.alephium.org/sdk/block/#block-subscription

**Comment by TropicalDog17** [comment]
@raduciobanu22 Hi, yes I would love to work on #4, @htiennv please add the WebSocket, thank you

**Comment by htiennv** [comment]
Hi @raduciobanu22, I'm just added websocket for subcribe new blocks. Can you take a look again? Thanks

**Pull request merged**
